language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
sudo: false
script: mvn clean package -Dgpg.skip=true
after_success:
  - if [ "$JAVA_HOME" = "/usr/lib/jvm/java-1.8.0-openjdk-amd64" ]; then mvn test cobertura:cobertura coveralls:report; fi
  - bash <(curl -s https://codecov.io/bash)
